//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tallyho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casing
    {
        public int CasingId { get; set; }
        public int StringId { get; set; }
        public int JointNumber { get; set; }
        public double Length { get; set; }
    
        public virtual String String { get; set; }
    }
}
